# Generated by Django 4.0 on 2021-12-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='total_experience',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
